import './globals.css'
import type { Metadata } from 'next';
import React from 'react';
import { UserProvider } from '@auth0/nextjs-auth0/client';

import Navbar from '../components/Navbar';
import Footer from '../components/Footer';




import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
   
    <html lang="en">
       <UserProvider>
    
      <body className={inter.className}>
      <Navbar />
      
      
        {children}
       
        <Footer/>
      </body>
  
      </UserProvider>
    </html>
   
  )
}
